# Generated by Django 5.2.16 on 2026-07-28 15:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="número do pregão"
                    ),
                ),
                ("object", models.TextField(blank=True, verbose_name="objeto")),
                (
                    "law",
                    models.CharField(
                        choices=[
                            ("8666", "Lei nº 8.666/1993"),
                            ("14133", "Lei nº 14.133/2021"),
                            ("OUTRA", "Outra"),
                        ],
                        default="14133",
                        max_length=10,
                        verbose_name="legislação",
                    ),
                ),
                (
                    "opening_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de abertura/sessão"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("HOMOLOGADO", "Homologado"),
                            ("FRACASSADO", "Fracassado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="situação",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "imported_from",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="origem da importação"
                    ),
                ),
                (
                    "requesting_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procurements",
                        to="contracts.organization",
                        verbose_name="OM do termo de referência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregão",
                "verbose_name_plural": "Pregões",
                "ordering": [
                    models.OrderBy(
                        models.F("opening_date"), descending=True, nulls_last=True
                    ),
                    "number",
                ],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="procurement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="contracts.procurement",
                verbose_name="pregão",
            ),
        ),
        migrations.CreateModel(
            name="ProcurementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "item_number",
                    models.CharField(max_length=40, verbose_name="item do pregão"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="código/TDV"
                    ),
                ),
                (
                    "nomenclature",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="nomenclatura"
                    ),
                ),
                ("specification", models.TextField(verbose_name="especificação")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="quantidade licitada",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="UN", max_length=30, verbose_name="unidade"
                    ),
                ),
                (
                    "unit_value_estimate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="valor unitário estimado",
                    ),
                ),
                (
                    "procurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="contracts.procurement",
                        verbose_name="pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do pregão",
                "verbose_name_plural": "Itens do pregão",
                "ordering": ["procurement", "item_number"],
            },
        ),
        migrations.AddField(
            model_name="contractitem",
            name="origin_procurement_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_items",
                to="contracts.procurementitem",
                verbose_name="item do pregão de origem",
            ),
        ),
        migrations.CreateModel(
            name="ProcurementItemDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="observações"
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_deliveries",
                        to="contracts.organization",
                        verbose_name="OM destino",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_locations",
                        to="contracts.procurementitem",
                        verbose_name="item do pregão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local de entrega do item",
                "verbose_name_plural": "Locais de entrega do item",
                "ordering": ["item", "destination"],
            },
        ),
        migrations.AddConstraint(
            model_name="procurementitem",
            constraint=models.UniqueConstraint(
                fields=("procurement", "item_number", "code"),
                name="unique_procurement_item_signature",
            ),
        ),
        migrations.AddConstraint(
            model_name="procurementitemdelivery",
            constraint=models.UniqueConstraint(
                fields=("item", "destination"),
                name="unique_procurement_item_destination",
            ),
        ),
    ]
