# Generated by Django 5.2.16 on 2026-07-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_procurement_contract_procurement_procurementitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplyorder",
            name="procurement_destinations",
            field=models.TextField(blank=True, verbose_name="OMs destino do pregão"),
        ),
    ]
