# Generated by Django 5.2.16 on 2026-07-30 18:51

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_supplyorder_procurement_destinations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procurement",
            name="object",
        ),
        migrations.RemoveField(
            model_name="procurementitem",
            name="specification",
        ),
        migrations.RemoveField(
            model_name="procurementitem",
            name="unit_value_estimate",
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="brand",
            field=models.CharField(blank=True, max_length=180, verbose_name="marca"),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="model",
            field=models.CharField(blank=True, max_length=180, verbose_name="modelo"),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="unit_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="valor unitário",
            ),
        ),
    ]
