# Generated by Django 5.2.16 on 2026-08-13 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_remove_procurement_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractchange",
            name="commitment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_changes",
                to="contracts.commitment",
                verbose_name="empenho relacionado",
            ),
        ),
        migrations.AddField(
            model_name="contractchange",
            name="commitment_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELECIONAR", "Selecionar empenho"),
                    ("CRIAR", "Criar empenho"),
                ],
                default="SELECIONAR",
                max_length=20,
                verbose_name="tipo de empenho",
            ),
        ),
        migrations.AddField(
            model_name="contractchange",
            name="deadline_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTRATO", "Prazo do contrato"),
                    ("EXECUCAO", "Prazo da execução"),
                ],
                default="CONTRATO",
                max_length=20,
                verbose_name="tipo de prazo",
            ),
        ),
        migrations.AddField(
            model_name="contractchange",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_changes",
                to="contracts.contractitem",
                verbose_name="item",
            ),
        ),
        migrations.AddField(
            model_name="contractchange",
            name="new_commitment_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="nova nota de empenho"
            ),
        ),
        migrations.AddField(
            model_name="contractchange",
            name="new_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="nova quantidade",
            ),
        ),
        migrations.AddField(
            model_name="contractchange",
            name="old_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="quantidade anterior",
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("QUANTIDADE", "Quantidade"),
                    ("PRAZO", "Prazo"),
                    ("VALOR", "Valor"),
                ],
                max_length=20,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="number",
            field=models.CharField(
                max_length=100, verbose_name="número do subprocesso"
            ),
        ),
    ]
