# Generated by Django 5.2.16 on 2026-08-16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_organization_address_cep"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitmentResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "budget_action",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="ação orçamentária"
                    ),
                ),
                ("ptres", models.CharField(blank=True, max_length=60, verbose_name="PTRES")),
                (
                    "credit_origin",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="origem do crédito",
                    ),
                ),
                ("pi", models.CharField(blank=True, max_length=80, verbose_name="PI")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="valor do recurso",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="contracts.commitment",
                        verbose_name="empenho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso do empenho",
                "verbose_name_plural": "Recursos do empenho",
                "ordering": ["pk"],
            },
        ),
    ]
