# Generated by Django 5.2.17 on 2026-08-16 03:58

import django.db.models.deletion
from django.db import migrations, models

import contracts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_commitmentresource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrativeprocess",
            options={
                "ordering": ["-opened_date"],
                "verbose_name": "Processo administrativo",
                "verbose_name_plural": "Processos administrativos",
            },
        ),
        migrations.AlterModelOptions(
            name="contractchange",
            options={
                "ordering": ["-request_date", "number"],
                "verbose_name": "Alteração contratual",
                "verbose_name_plural": "Alterações contratuais",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-reference_date", "-created_at"],
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
            },
        ),
        migrations.RemoveConstraint(
            model_name="administrativeprocess",
            name="unique_administrative_process",
        ),
        migrations.RemoveConstraint(
            model_name="contractchange",
            name="unique_contract_change",
        ),
        migrations.RemoveField(
            model_name="contractchange",
            name="signed_date",
        ),
        migrations.RemoveField(
            model_name="contractchange",
            name="status",
        ),
        migrations.RemoveField(
            model_name="document",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="commitmentresource",
            name="number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="nota de empenho"
            ),
        ),
        migrations.AlterField(
            model_name="administrativeprocess",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="prazo"),
        ),
        migrations.AlterField(
            model_name="administrativeprocess",
            name="number",
            field=models.CharField(max_length=100, verbose_name="número do processo"),
        ),
        migrations.AlterField(
            model_name="administrativeprocess",
            name="sanction",
            field=models.TextField(blank=True, verbose_name="sanção aplicada"),
        ),
        migrations.AlterField(
            model_name="administrativeprocess",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTO", "Aberto"),
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("SUSPENSO", "Suspenso"),
                    ("ENCERRADO", "Encerrado"),
                ],
                default="ABERTO",
                max_length=20,
                verbose_name="situação",
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("QUANTIDADE", "Alteração de Quantidade"),
                    ("PRAZO", "Alteração de Prazo"),
                    ("VALOR", "Alteração de Valor"),
                ],
                max_length=20,
                verbose_name="tipo de alteração",
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="commitment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changes",
                to="contracts.commitment",
                verbose_name="empenho para alteração de valor",
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="commitment_mode",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="modalidade do empenho"
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="deadline_scope",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="escopo da alteração de prazo"
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changes",
                to="contracts.contractitem",
                verbose_name="item",
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="new_commitment_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="número do novo empenho"
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="new_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="novo prazo"),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="new_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="nova quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="number",
            field=models.CharField(max_length=100, verbose_name="número da alteração"),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="old_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="prazo anterior"
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="old_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="quantidade anterior",
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="request_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="data da solicitação"
            ),
        ),
        migrations.AlterField(
            model_name="contractchange",
            name="value_change",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                verbose_name="alteração do valor",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("LEGAL", "Legal/Contratual"),
                    ("FINANCIAL", "Financeiro"),
                    ("TECHNICAL", "Técnico"),
                    ("CORRESPONDENCE", "Correspondência"),
                    ("DELIVERY", "Entrega/Recebimento"),
                    ("OTHER", "Outro"),
                ],
                default="OTHER",
                max_length=30,
                verbose_name="categoria",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to="contracts/documents/",
                validators=[
                    contracts.validators.validate_document_extension,
                    contracts.validators.validate_file_size,
                ],
                verbose_name="arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=240, verbose_name="título"),
        ),
    ]
